# This file is part of MCToolkit.
# Copyright (C) 2026 Hunter Picard
#
# MCToolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MCToolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MCToolkit. If not, see <https://www.gnu.org/licenses/>.


"""Inventory polymer chains, ligands, metals, and solvent from crystallographic files."""

from __future__ import annotations


from .structure_atoms import (
    parse_structure_atoms,
    pocket_view_plan,
    _dist_sq,
    _is_hydrogen,
    _pdb_from_atoms,
    _residue_kinds_from_atoms,
)
from .structure_cif import (
    add_cif_chem_bond,
    append_missing_cif_residues,
    attach_cif_chem_comp,
    atoms_to_mmcif,
    cif_comment_remarks,
    cif_has_component_bonds,
    cif_viewer_bond_tables,
    delete_cif_atoms,
    delete_cif_residues,
    format_chem_comp_cif_loops,
    parse_cif_chem_comp_atoms,
    parse_cif_chem_comp_bonds,
    pdb_to_mmcif,
    rebuild_hydrogen_chem_bonds,
    rebuild_hydrogen_chem_tables,
    remove_cif_chem_bond,
    repair_cif_hydrogen_chem_bonds,
)
from .structure_component_types import (
    AA_ONE_TO_THREE,
    AA_THREE_TO_ONE,
    AMINO_ACIDS,
    CifChemAtom,
    CifChemBond,
    HETERO_SEQUENCE_LETTERS,
    LoadedStructure,
    METAL_ELEMENTS,
    METAL_RESIDUES,
    NUCLEIC_ACIDS,
    NUCLEIC_THREE_TO_ONE,
    POLAR_HEAVY_ELEMENTS,
    PocketViewPlan,
    PolymerChain,
    PolymerResidue,
    SEQ_LETTER_LIGAND,
    SEQ_LETTER_METAL,
    SEQ_LETTER_OTHER,
    SEQ_LETTER_WATER,
    SEQUENCE_ALPHABET,
    STRUCTURE_FORMAT_BY_SUFFIX,
    SequenceEdit,
    StructureAtom,
    StructureComponent,
    VALID_SEQUENCE_LETTERS,
    WATER_RESIDUES,
    _ResidueBucket,
    _atom_key4,
    _norm_chain,
    _optional_float,
    _residue_key3,
)
from .structure_inventory import (
    add_pdb_conect,
    amino_acid_letter,
    component_id_for_atom,
    delete_pdb_atoms,
    delete_pdb_residues,
    diff_sequence_edit,
    letter_to_resn,
    load_structure_file,
    parse_polymer_sequences,
    parse_structure_components,
    pdb_conect_partners,
    pdb_serial_for_atom,
    polymer_residue_for_atom,
    polymer_sequence_entries,
    remove_pdb_conect,
    rewrite_pdb_residue_names,
    scope_structure_component,
    sequence_letter_for,
    sniff_structure_format,
    viewer_format_for,
    _pdb_residue_key,
)

__all__ = [
    "AA_ONE_TO_THREE",
    "AA_THREE_TO_ONE",
    "AMINO_ACIDS",
    "CifChemAtom",
    "CifChemBond",
    "HETERO_SEQUENCE_LETTERS",
    "LoadedStructure",
    "METAL_ELEMENTS",
    "METAL_RESIDUES",
    "NUCLEIC_ACIDS",
    "NUCLEIC_THREE_TO_ONE",
    "POLAR_HEAVY_ELEMENTS",
    "PocketViewPlan",
    "PolymerChain",
    "PolymerResidue",
    "SEQ_LETTER_LIGAND",
    "SEQ_LETTER_METAL",
    "SEQ_LETTER_OTHER",
    "SEQ_LETTER_WATER",
    "SEQUENCE_ALPHABET",
    "STRUCTURE_FORMAT_BY_SUFFIX",
    "SequenceEdit",
    "StructureAtom",
    "StructureComponent",
    "VALID_SEQUENCE_LETTERS",
    "WATER_RESIDUES",
    "add_cif_chem_bond",
    "add_pdb_conect",
    "amino_acid_letter",
    "append_missing_cif_residues",
    "attach_cif_chem_comp",
    "atoms_to_mmcif",
    "cif_comment_remarks",
    "cif_has_component_bonds",
    "cif_viewer_bond_tables",
    "component_id_for_atom",
    "delete_cif_atoms",
    "delete_cif_residues",
    "delete_pdb_atoms",
    "delete_pdb_residues",
    "diff_sequence_edit",
    "format_chem_comp_cif_loops",
    "letter_to_resn",
    "load_structure_file",
    "parse_cif_chem_comp_atoms",
    "parse_cif_chem_comp_bonds",
    "parse_polymer_sequences",
    "parse_structure_atoms",
    "parse_structure_components",
    "pdb_conect_partners",
    "pdb_serial_for_atom",
    "pdb_to_mmcif",
    "pocket_view_plan",
    "polymer_residue_for_atom",
    "polymer_sequence_entries",
    "rebuild_hydrogen_chem_bonds",
    "rebuild_hydrogen_chem_tables",
    "remove_cif_chem_bond",
    "remove_pdb_conect",
    "repair_cif_hydrogen_chem_bonds",
    "rewrite_pdb_residue_names",
    "scope_structure_component",
    "sequence_letter_for",
    "sniff_structure_format",
    "viewer_format_for",
    "_ResidueBucket",
    "_atom_key4",
    "_dist_sq",
    "_is_hydrogen",
    "_norm_chain",
    "_optional_float",
    "_pdb_from_atoms",
    "_pdb_residue_key",
    "_residue_key3",
    "_residue_kinds_from_atoms",
]
