# This file is part of MolManager.
# Copyright (C) 2026 Hunter Picard
#
# MolManager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MolManager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MolManager. If not, see <https://www.gnu.org/licenses/>.

"""Shared helpers for plots docked beside the main compound table."""

from __future__ import annotations

from .dockable_plot_chrome import (
    apply_plot_chrome_glyphs,
    confirm_close_plot,
    discard_host_dialog_after_dock,
    handle_floating_plot_close_event,
    hide_plot_options_dialog,
    make_add_to_main_button,
    make_clear_selection_button,
    make_close_plot_button,
    make_plot_options_button,
    make_plot_options_dialog,
    make_send_window_button,
    request_close_plot_widget,
    show_plot_options_dialog,
)
from .dockable_plot_constants import (
    PLOT_BODY_MARGINS,
    PLOT_BODY_SPACING,
    PLOT_PANEL_BASE_MINIMUM_WIDTH,
    PLOT_PANEL_COLLAPSED_WIDTH,
    PLOT_PANEL_DEFAULT_WIDTH,
    _DOCK_LEADING_OPTS_ATTRS,
    _FOOTER_TEXT_FONT_PX,
    _GLYPH_BTN_SIZE,
    _GLYPH_ICON_SIZE,
)
from .dockable_plot_embed import (
    adopt_dock_header_buttons,
    embed_in_plot_pane,
    is_dockable_plot_widget,
    is_dockable_workspace_widget,
    iter_dock_header_buttons,
    iter_dock_leading_opts_buttons,
    iter_dock_send_window_buttons,
    iter_dock_trailing_close_buttons,
    iter_plot_selection_views,
    parent_change_chrome_suspended,
    plot_embedded_minimum_width,
    plot_embedded_preferred_width,
    restore_dock_header_buttons,
    suspend_parent_change_chrome,
    sync_docked_footer_bar,
    sync_footer_on_parent_change,
    unembed_from_plot_pane,
)
from .dockable_plot_glyphs import (
    add_centered_browser_nav,
    add_to_main_glyph_icon,
    browser_nav_glyph_icon,
    clear_selection_glyph_icon,
    pane_close_glyph_icon,
    pane_nav_arrow_glyph_icon,
    plot_options_glyph_icon,
    select_row_glyph_icon,
    send_to_window_glyph_icon,
    style_browser_nav_arrow,
    style_browser_nav_buttons,
    style_browser_select_button,
    style_plot_chrome_glyph_button,
    style_plot_footer_text_button,
    style_plot_pane_close_button,
    style_plot_pane_nav_arrow,
    style_plot_pane_title_edit,
    style_floating_plot_title_edit,
)
from .dockable_plot_title import (
    PlotTitlesControls,
    begin_floating_title_edit,
    cancel_floating_title_edit,
    commit_floating_title_edit,
    ensure_floating_title_edit,
    plot_widget_display_title,
    position_floating_title_edit,
    refresh_floating_title_edit,
    resolve_plot_title_text,
    sync_floating_title_chrome,
)

__all__ = [
    "PLOT_BODY_MARGINS",
    "PLOT_BODY_SPACING",
    "PLOT_PANEL_BASE_MINIMUM_WIDTH",
    "PLOT_PANEL_COLLAPSED_WIDTH",
    "PLOT_PANEL_DEFAULT_WIDTH",
    "PlotTitlesControls",
    "_DOCK_LEADING_OPTS_ATTRS",
    "_FOOTER_TEXT_FONT_PX",
    "_GLYPH_BTN_SIZE",
    "_GLYPH_ICON_SIZE",
    "add_centered_browser_nav",
    "add_to_main_glyph_icon",
    "adopt_dock_header_buttons",
    "apply_plot_chrome_glyphs",
    "begin_floating_title_edit",
    "browser_nav_glyph_icon",
    "cancel_floating_title_edit",
    "clear_selection_glyph_icon",
    "commit_floating_title_edit",
    "confirm_close_plot",
    "discard_host_dialog_after_dock",
    "embed_in_plot_pane",
    "ensure_floating_title_edit",
    "handle_floating_plot_close_event",
    "hide_plot_options_dialog",
    "is_dockable_plot_widget",
    "is_dockable_workspace_widget",
    "iter_dock_header_buttons",
    "iter_dock_leading_opts_buttons",
    "iter_dock_send_window_buttons",
    "iter_dock_trailing_close_buttons",
    "iter_plot_selection_views",
    "make_add_to_main_button",
    "make_clear_selection_button",
    "make_close_plot_button",
    "make_plot_options_button",
    "make_plot_options_dialog",
    "make_send_window_button",
    "pane_close_glyph_icon",
    "pane_nav_arrow_glyph_icon",
    "parent_change_chrome_suspended",
    "plot_embedded_minimum_width",
    "plot_embedded_preferred_width",
    "plot_options_glyph_icon",
    "plot_widget_display_title",
    "position_floating_title_edit",
    "refresh_floating_title_edit",
    "request_close_plot_widget",
    "resolve_plot_title_text",
    "restore_dock_header_buttons",
    "select_row_glyph_icon",
    "send_to_window_glyph_icon",
    "show_plot_options_dialog",
    "style_browser_nav_arrow",
    "style_browser_nav_buttons",
    "style_browser_select_button",
    "style_floating_plot_title_edit",
    "style_plot_chrome_glyph_button",
    "style_plot_footer_text_button",
    "style_plot_pane_close_button",
    "style_plot_pane_nav_arrow",
    "style_plot_pane_title_edit",
    "suspend_parent_change_chrome",
    "sync_docked_footer_bar",
    "sync_floating_title_chrome",
    "sync_footer_on_parent_change",
    "unembed_from_plot_pane",
]
